# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/dds/dds.srcs/sources_1/bd/dds/ip/dds_dds_compiler_0_0/dds_dds_compiler_0_0.xci
# IP: The module: 'dds_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/dds/dds.gen/sources_1/bd/dds/ip/dds_dds_compiler_0_0/dds_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/dds/dds.srcs/sources_1/bd/dds/ip/dds_dds_compiler_0_0/dds_dds_compiler_0_0.xci
# IP: The module: 'dds_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/dds/dds.gen/sources_1/bd/dds/ip/dds_dds_compiler_0_0/dds_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
