# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dds/dds.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds || ORIG_REF_NAME==dds} -quiet] -quiet

# IP: bd/dds/ip/dds_dds_compiler_0_0/dds_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_dds_compiler_0_0 || ORIG_REF_NAME==dds_dds_compiler_0_0} -quiet] -quiet

# IP: bd/dds/ip/dds_xlslice_0_0/dds_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_xlslice_0_0 || ORIG_REF_NAME==dds_xlslice_0_0} -quiet] -quiet

# IP: bd/dds/ip/dds_xlslice_0_1/dds_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_xlslice_0_1 || ORIG_REF_NAME==dds_xlslice_0_1} -quiet] -quiet

# IP: bd/dds/ip/dds_sim_clk_gen_0_0/dds_sim_clk_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_sim_clk_gen_0_0 || ORIG_REF_NAME==dds_sim_clk_gen_0_0} -quiet] -quiet

# XDC: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/dds/dds.gen/sources_1/bd/dds/dds_ooc.xdc
