-d C:\Users\Martin Stoyanov\IdeaProjects\va3aui\verilog\rx\impl\gwsynthesis\rx.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Martin Stoyanov\IdeaProjects\va3aui\verilog\rx\src\rx.cst
-cfg C:\Users\Martin Stoyanov\IdeaProjects\va3aui\verilog\rx\impl\pnr\device.cfg
-sdc C:\Users\Martin Stoyanov\IdeaProjects\va3aui\verilog\rx\src\rx.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
