-d C:\Users\Martin Stoyanov\IdeaProjects\va3aui\verilog\rx\impl\gwsynthesis\rx.vg
-p GW2AR-18C-QFN88-7
-pn GW2AR-LV18QN88C7/I6
-cst C:\Users\Martin Stoyanov\IdeaProjects\va3aui\verilog\rx\src\rx.cst
-cfg C:\Users\Martin Stoyanov\IdeaProjects\va3aui\verilog\rx\impl\pnr\device.cfg
-sdc C:\Users\Martin Stoyanov\IdeaProjects\va3aui\verilog\rx\src\rx.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
