# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/rx/rx.srcs/sources_1/bd/rx/ip/rx_c_addsub_0_0/rx_c_addsub_0_0.xci
# IP: The module: 'rx_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/rx/rx.gen/sources_1/bd/rx/ip/rx_c_addsub_0_0/rx_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/rx/rx.srcs/sources_1/bd/rx/ip/rx_c_addsub_0_0/rx_c_addsub_0_0.xci
# IP: The module: 'rx_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/rx/rx.gen/sources_1/bd/rx/ip/rx_c_addsub_0_0/rx_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
