# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/rx/rx.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx || ORIG_REF_NAME==rx} -quiet] -quiet

# IP: bd/rx/ip/rx_mult_gen_0_0/rx_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_mult_gen_0_0 || ORIG_REF_NAME==rx_mult_gen_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_mult_gen_0_2/rx_mult_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_mult_gen_0_2 || ORIG_REF_NAME==rx_mult_gen_0_2} -quiet] -quiet

# IP: bd/rx/ip/rx_dds_compiler_0_0/rx_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_dds_compiler_0_0 || ORIG_REF_NAME==rx_dds_compiler_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_xlslice_1_0/rx_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_xlslice_1_0 || ORIG_REF_NAME==rx_xlslice_1_0} -quiet] -quiet

# IP: bd/rx/ip/rx_xlslice_1_1/rx_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_xlslice_1_1 || ORIG_REF_NAME==rx_xlslice_1_1} -quiet] -quiet

# IP: bd/rx/ip/rx_cic_compiler_0_0/rx_cic_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_cic_compiler_0_0 || ORIG_REF_NAME==rx_cic_compiler_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_cic_compiler_0_1/rx_cic_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_cic_compiler_0_1 || ORIG_REF_NAME==rx_cic_compiler_0_1} -quiet] -quiet

# IP: bd/rx/ip/rx_fir_compiler_0_0/rx_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_fir_compiler_0_0 || ORIG_REF_NAME==rx_fir_compiler_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_fir_compiler_0_1/rx_fir_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_fir_compiler_0_1 || ORIG_REF_NAME==rx_fir_compiler_0_1} -quiet] -quiet

# IP: bd/rx/ip/rx_sim_clk_gen_0_0/rx_sim_clk_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_sim_clk_gen_0_0 || ORIG_REF_NAME==rx_sim_clk_gen_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_fir_compiler_2_0/rx_fir_compiler_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_fir_compiler_2_0 || ORIG_REF_NAME==rx_fir_compiler_2_0} -quiet] -quiet

# IP: bd/rx/ip/rx_c_addsub_0_0/rx_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_c_addsub_0_0 || ORIG_REF_NAME==rx_c_addsub_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_xlslice_1_2/rx_xlslice_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_xlslice_1_2 || ORIG_REF_NAME==rx_xlslice_1_2} -quiet] -quiet

# IP: bd/rx/ip/rx_xlslice_0_1/rx_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_xlslice_0_1 || ORIG_REF_NAME==rx_xlslice_0_1} -quiet] -quiet

# XDC: c:/Users/Martin Stoyanov/IdeaProjects/va3aui/verilog/rx/rx.gen/sources_1/bd/rx/rx_ooc.xdc
